spring:
  application:
    name: microservice-discovery-eureka-ha
---
server:
  port: 8761
spring:
  # 指定profile=peer1
  profiles: peer1
eureka:
  instance:
    # 指定当profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    service-url:
      # 将自己注册到peer2、peer3这个Eureka上面去
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
---
server:
  port: 8762
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
---
server:
  port: 8763
spring:
  profiles: peer3
eureka:
  instance:
    hostname: peer3
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
    