# 服务消费者
spring:
  application:
    name: microservice-consumer-movie-ribbon-properties-customizing
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
# 设置microservice-provider-user微服务使用加权方式实现负载均衡
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

    
    