# 服务消费者
spring:
  application:
    name: microservice-consumer-movie-ribbon-without-eureka
server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
#配置Ribbon脱离Eureka使用
ribbon:
  eureka:
    enabled: false
# 设置microservice-provider-user微服务只能是端口为7900的使用本ribbon组件
microservice-provider-user:
  ribbon:
    listOfServers: localhost:7900

    
    