server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/dear_alice_moon/config-repo
          username: 
          password: 
  application:
    name: microservice-config-server-eureka

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true
  