# 服务消费者
spring:
  application:
    name: microservice-consumer-movie
server:
  port: 7901
user:
  userServicePath: http://localhost:7900/simple/
eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true